/*
生成されたこのファイルは、
この管理グローバルクラスの実際のソースコードではありません。
この参照のみのファイルには、クラスのグローバルコンストラクタ、
メソッド、変数、プロパティが表示されます。
コードをコンパイルできるようにするには、すべてのメソッドで null を返します。
*/
global virtual class BaseController {
    global static Integer ANDROID;
    global static Integer BLACKBERRY;
    global static Integer IPHONE_IPAD;
    global static Integer PC;
    global BaseController() {

    }
    global virtual String getAccessPoint() {
        return null;
    }
    global virtual String getCanvasDesign() {
        return null;
    }
    global virtual String getCanvasGuide() {
        return null;
    }
    global virtual String getCanvasParamsBase64() {
        return null;
    }
    global virtual String getCanvasPreview() {
        return null;
    }
    global virtual String getCanvasPrinter() {
        return null;
    }
    global virtual String getCanvasSignatureBase64() {
        return null;
    }
    global virtual String getCanvasUsage() {
        return null;
    }
    global virtual String getNameSpace() {
        return null;
    }
    global virtual Boolean getPermissionsCreateVisualforcePage() {
        return null;
    }
    global virtual String getResourceRootPath() {
        return null;
    }
    global virtual String getSvfCloudServiceHost() {
        return null;
    }
    global virtual Boolean getViewAllPrinters() {
        return null;
    }
}
