/*
生成されたこのファイルは、
この管理グローバルクラスの実際のソースコードではありません。
この参照のみのファイルには、クラスのグローバルコンストラクタ、
メソッド、変数、プロパティが表示されます。
コードをコンパイルできるようにするには、すべてのメソッドで null を返します。
*/
global class PreviewController extends svfcloud.BaseController {
    global String buttonFullName {
        get;
        set;
    }
    global String dir {
        get;
        set;
    }
    global String errorMessage {
        get;
        set;
    }
    global String id {
        get;
        set;
    }
    global String key {
        get;
        set;
    }
    global String layout {
        get;
        set;
    }
    global String q1 {
        get;
        set;
    }
    global String q2 {
        get;
        set;
    }
    global String q3 {
        get;
        set;
    }
    global String q4 {
        get;
        set;
    }
    global String q5 {
        get;
        set;
    }
    global String q6 {
        get;
        set;
    }
    global String q7 {
        get;
        set;
    }
    global String q8 {
        get;
        set;
    }
    global String q9 {
        get;
        set;
    }
    global String query {
        get;
        set;
    }
    global String sObjectTypeName {
        get;
        set;
    }
    global String sortKey {
        get;
        set;
    }
    global PreviewController() {

    }
    global PreviewController(ApexPages.StandardController controller) {

    }
    global PreviewController(ApexPages.StandardSetController controller) {

    }
    global System.PageReference getPreviewReference() {
        return null;
    }
    global void init() {

    }
}
